=== cristianoramon/distXMLNfe/Nfs/BackPFI/SqlNfs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 U (http://www.altova.com) by Administrador (EMBRACE) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Root">
		<xs:annotation>
			<xs:documentation>Sql para autorização da Nota</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Sql">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Select">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="SelCo1" type="xs:string"/>
										<xs:element name="SelCo2" type="xs:string"/>
										<xs:element name="SelCo3" type="xs:string"/>
										<xs:element name="SelFrom">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="SelFromTab1" type="xs:string"/>
													<xs:element name="SelFromTab2" type="xs:string"/>
													<xs:element name="SelFromTab3" type="xs:string"/>
													<xs:element name="SelFromTab4" type="xs:string"/>
													<xs:element name="SelFromTab5" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="SelWhere">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="SelWhereCond1" type="xs:string"/>
													<xs:element name="SelWhereCond2" type="xs:string"/>
													<xs:element name="SelWhereCond3" type="xs:string"/>
													<xs:element name="SelWhereCond4" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== cristianoramon/distXMLNfe/Nfs/BackPFI/Nfs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 U (http://www.altova.com) by Administrador (EMBRACE) -->
<!--Sample XML file generated by XMLSpy v2006 U (http://www.altova.com)-->
<Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\WebPhp5\web\Nfs\xml\SqlNfs.xsd">
	<Sql>
		<Select>
			<SelCo1>s.nf ,  </SelCo1>
			<SelCo2> s.emissao ,  </SelCo2>
			<SelCo3>  s.valor </SelCo3>
			
			
			<SelFrom>
				<SelFromTab1>saidas s,</SelFromTab1>
				<SelFromTab2>itens_saidas it</SelFromTab2>
				<SelFromTab3/>
				<SelFromTab4/>
				<SelFromTab5/>
			</SelFrom>
			<SelWhere>
				<SelWhereCond1>where s.nf = it.nf</SelWhereCond1>
				<SelWhereCond2>and   s.serie = it.serie</SelWhereCond2>
				<SelWhereCond3>and   s.filial = it.filial</SelWhereCond3>
				<SelWhereCond4>and   s.filial = '001'</SelWhereCond4>
			</SelWhere>
		</Select>
	</Sql>
</Root>
